//
//  MovieListInterfaces.swift
//  MovieDBApp
//
//  Created by Cem Kazım on 1.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieListWireframeInterface: WireframeInterface {
}

protocol MovieListViewInterface: ViewInterface {
}

protocol MovieListPresenterInterface: PresenterInterface {
}

protocol MovieListFormatterInterface: FormatterInterface {
}

protocol MovieListInteractorInterface: InteractorInterface {
}
