//
//  PopularMovieListViewController.swift
//  MovieDBApp
//
//  Created by Cem Kazım on 1.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PopularMovieListViewController: UIViewController {
    
    private var movieListCollectionView: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.estimatedItemSize = CGSize(width: 200, height: 200)
        layout.scrollDirection = .vertical
        let view = UICollectionView(frame: .zero, collectionViewLayout: layout)
        view.translatesAutoresizingMaskIntoConstraints = false
        view.setCollectionViewLayout(layout, animated: true)
        view.backgroundColor = .clear
        view.backgroundView = UIView.init(frame: .zero)
        return view
    }()
    private lazy var loadMoreButton: UIButton = {
        let button = UIButton()
        button.translatesAutoresizingMaskIntoConstraints = false
        button.backgroundColor = .black
        button.setTitle(Constants.loadMoreButtonText, for: .normal)
        button.addTarget(self, action: #selector(loadMoreButtonClicked), for: .touchUpInside)
        button.isHidden = true
        button.titleLabel?.font = UIFont(name: Constants.camptonMediumFontText, size: 12)
        button.titleLabel?.textColor = .white
        return button
    }()
    private lazy var viewModel = PopularMovieListViewModel()
    private var movieList = [ResultModel]()
    private var starredMovieIdList = [Int]()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        getMovieData()
    }
    
    @objc func loadMoreButtonClicked() {
        viewModel.increasePageCount()
        viewModel.getData()
        movieListCollectionView.reloadData()
        loadMoreButton.isHidden = true
    }
}

extension PopularMovieListViewController {
    
    private func setupView() {
        view.backgroundColor = .white
        title = Constants.popularMovieListTitle
        addSubviews()
        setupConstraints()
        setupCollectionView()
    }
    
    private func getMovieData() {
        viewModel = PopularMovieListViewModel(delegate: self)
        viewModel.getData()
        viewModel.getStarredMovieData()
    }
    
    private func addSubviews() {
        view.addSubview(movieListCollectionView)
        view.addSubview(loadMoreButton)
    }
    
    private func setupConstraints() {
        NSLayoutConstraint.activate([
            movieListCollectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            movieListCollectionView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
            movieListCollectionView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
            movieListCollectionView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
            
            loadMoreButton.bottomAnchor.constraint(equalTo: movieListCollectionView.bottomAnchor, constant: -10),
            loadMoreButton.heightAnchor.constraint(equalToConstant: 40),
            loadMoreButton.widthAnchor.constraint(equalToConstant: 100),
            loadMoreButton.centerXAnchor.constraint(equalTo: movieListCollectionView.centerXAnchor)
        ])
    }
    
    private func setupCollectionView() {
        movieListCollectionView.delegate = self
        movieListCollectionView.dataSource = self
        movieListCollectionView.register(PopularMovieListCollectionViewCell.self, forCellWithReuseIdentifier: Constants.popularMovieListCollectionViewCellID)
    }
}

extension PopularMovieListViewController: UICollectionViewDelegate, UICollectionViewDataSource {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return movieList.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        if let cell = collectionView.dequeueReusableCell(withReuseIdentifier: Constants.popularMovieListCollectionViewCellID, for: indexPath) as? PopularMovieListCollectionViewCell {
            cell.setMovieData(popularMovieList: movieList, starredMovieIdList: starredMovieIdList, indexPath: indexPath)
            return cell
        } else {
            return UICollectionViewCell()
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        if movieList.count == viewModel.getPageItemCount() * viewModel.getCurrentPageNumber() {
            if indexPath.row == movieList.count - 1 {
                loadMoreButton.isHidden = false
            }
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if let movieId = movieList[indexPath.row].id {
            let movieDetailViewController = MovieDetailViewController()
            movieDetailViewController.selectedMovieId = movieId
            let isStarred = starredMovieIdList.contains(where: { $0 == movieId })
            movieDetailViewController.isMovieStarred = isStarred
            navigationController?.pushViewController(movieDetailViewController, animated: true)
        }
    }
}

extension PopularMovieListViewController: PopularMovieListViewModelDelegate {
    
    func getPopularMovie(with popularMovieList: [ResultModel]) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            self.movieList = popularMovieList
            self.movieListCollectionView.reloadData()
        }
    }
    
    func getStarredMovie(with starredMovieIdList: [Int]) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            self.starredMovieIdList = starredMovieIdList
            self.movieListCollectionView.reloadData()
        }
    }
}
